/**
 * Expense Classification Utility — Phase 2B
 *
 * Provides a single source of truth for separating expenses into:
 * - Fixed (recurring bill payments): recurring_expense_id IS NOT NULL
 * - Variable (discretionary spending): recurring_expense_id IS NULL
 *
 * Used by rate, velocity, and projection calculations that must not
 * treat fixed monthly bills as variable daily spending.
 *
 * Accounting totals (budget remaining, financial health, category breakdowns)
 * continue to use ALL expenses — this utility is specifically for behavioral
 * metrics (burn rate, velocity, forecasting).
 *
 * @module statistics/expenseClassification
 */

import type { Expense } from '../../store/useStore';

/**
 * Result of classifying a set of expenses into fixed and variable buckets.
 */
export interface ClassifiedExpenses {
  /** All expenses (fixed + variable) — use for accounting totals */
  readonly all: readonly Expense[];
  /** Expenses linked to a recurring bill (recurring_expense_id IS NOT NULL) */
  readonly fixed: readonly Expense[];
  /** Expenses NOT linked to a recurring bill (recurring_expense_id IS NULL) */
  readonly variable: readonly Expense[];
  /** Sum of all expense amounts */
  readonly totalAmount: number;
  /** Sum of fixed (recurring) expense amounts */
  readonly fixedAmount: number;
  /** Sum of variable (non-recurring) expense amounts */
  readonly variableAmount: number;
}

/**
 * Determines whether an expense is a fixed recurring bill payment.
 *
 * An expense is considered "fixed" if it was generated by paying a
 * recurring bill (i.e., recurring_expense_id is populated).
 *
 * @param expense - The expense to classify
 * @returns true if the expense is a recurring bill payment
 */
export function isFixedRecurringExpense(expense: Expense): boolean {
  return expense.recurring_expense_id != null && expense.recurring_expense_id !== '';
}

/**
 * Classifies a list of expenses into fixed (recurring) and variable buckets.
 *
 * This is the canonical classification function used by all rate/velocity/
 * projection calculations to separate fixed monthly obligations from
 * variable daily spending behavior.
 *
 * @param expenses - Array of expenses to classify
 * @returns Classified expenses with pre-computed totals
 */
export function classifyExpenses(expenses: readonly Expense[]): ClassifiedExpenses {
  const fixed: Expense[] = [];
  const variable: Expense[] = [];
  let fixedAmount = 0;
  let variableAmount = 0;

  for (const expense of expenses) {
    if (isFixedRecurringExpense(expense)) {
      fixed.push(expense);
      fixedAmount += expense.amount;
    } else {
      variable.push(expense);
      variableAmount += expense.amount;
    }
  }

  return {
    all: expenses,
    fixed,
    variable,
    totalAmount: fixedAmount + variableAmount,
    fixedAmount,
    variableAmount,
  };
}
